availableSecrets:
  secretManager:
    - versionName: "projects/nectar-bazaar/secrets/rubygems-api-key/versions/latest"
      env: 'RUBYGEMS_API_KEY'

steps:

  - id: "Build base image"
    name: 'gcr.io/cloud-builders/docker'
    waitFor: []
    args:
      - "build"
      - "."
      - "-t"
      - "test-image:1.0.0"

  - id: "Pull Kind Test Runner Image"
    name: 'gcr.io/cloud-builders/docker'
    waitFor: []
    args:
      - "pull"
      - "us-central1-docker.pkg.dev/nectar-bazaar/public/kind-test-runner:0.0.2"

  - id: "Run Tests in kind cluster"
    name: 'gcr.io/cloud-builders/docker'
    waitFor:
      - "Build base image"
      - "Pull Kind Test Runner Image"
    args:
      - "run"
      - "-v"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "--net=host"
      - "us-central1-docker.pkg.dev/nectar-bazaar/public/kind-test-runner:0.0.2"

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Publish Gem'
    entrypoint: 'bash'
    waitFor:
      - "Build base image"
      - 'Run tests and push coverage'

    secretEnv: ['RUBYGEMS_API_KEY']

    args:
      - '-c'
      - 'docker run
      --env RUBYGEMS_API_KEY=$$RUBYGEMS_API_KEY
      test-image:1.0.0
      publish'