apiVersion: v1
kind: Pod
metadata:
  name: hello-kerbi
  namespace: default
spec:
  containers:
  - name: main
    image: nginx

---

apiVersion: v1
kind: Service
metadata:
  name: hello-kerbi
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: hello-kerbi
  ports:
  - port: 80
